name: Video Watermark Remover  # 任务名字
on: 
  # push:                        # 触发条件：当你 push 代码时
  workflow_dispatch:      # 保留这个，方便你偶尔在网页上手动点
  repository_dispatch:     # 增加这个，接收来自 Python API 的请求
    types: [start_processing]  # 必须匹配你 Python data 里的 event_type

jobs:
  remove-watermark:            # Job 名字
    runs-on: ubuntu-latest     # 运行环境：最新版 Ubuntu

    steps:
      # - name: Checkout Code    # 第一步：把你的代码拉取到云端服务器
      #   uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          # --- Install Latest Ffmpeg ---
          wget -q https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
          mkdir ffmpeg_latest
          tar -xf ffmpeg-master-latest-linux64-gpl.tar.xz -C ffmpeg_latest --strip-components=1
          echo "$(pwd)/ffmpeg_latest/bin" >> $GITHUB_PATH

          # --- Install Crypto Lib ---
          pip install cryptography

      - name: Transcode Video
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          RN_SJC_01_IP: ${{ secrets.RN_SJC_01_IP }}
          RN_SJC_01_SSH_KEY: ${{ secrets.RN_SJC_01_SSH_KEY }}
          RN_SJC_02_IP: ${{ secrets.RN_SJC_02_IP }}
          RN_SJC_02_SSH_KEY: ${{ secrets.RN_SJC_02_SSH_KEY }}
          CRYPTO_KEY: ${{ secrets.CRYPTO_KEY }}
          ENCRYPTED_NAME: ${{ github.event.client_payload.encrypted_name }}
        run: |

          # --- Step 0: Prepare Environment ---
          set +x

          FILE_NAME=$(python3 -c "
          from cryptography.fernet import Fernet
          import os
          f = Fernet(os.environ['CRYPTO_KEY'].encode())
          print(f.decrypt(os.environ['ENCRYPTED_NAME'].encode()).decode())
                    ")

          echo "::add-mask::$FILE_NAME"

          HOST_NAME="${{ github.event.client_payload.host_name }}"

          if [ "${HOST_NAME}" == "rn-sjc-02" ]; then
            echo "${RN_SJC_02_SSH_KEY}" > id_ed25519
            VPS_IP="${RN_SJC_02_IP}"
          elif [ "${HOST_NAME}" == "rn-sjc-01" ]; then
            echo "${RN_SJC_01_SSH_KEY}" > id_ed25519
            VPS_IP="${RN_SJC_01_IP}"
          else
            echo "Error: Unknown host_name ${HOST_NAME}"
            exit 1
          fi
          chmod 600 id_ed25519
          echo "Step 0 is Done"


          # --- Step 1: Fetch Video from VPS ---
          rsync -avP --remove-source-files -e "ssh -i id_ed25519 -o StrictHostKeyChecking=no" \
            ${USER_NAME}@${VPS_IP}:pending/"${FILE_NAME}" ./"${FILE_NAME}"
          echo "Step 1 is Done"


          # --- Step 2: Process Transcode ---
          ffmpeg -y -i ./${FILE_NAME} \
            -filter:v:0 "delogo=x=18:y=15:w=63:h=17:show=0" \
            -map 0:v:0 -map 0:a:0? -map 0:v:1? \
            -c:v:0 libx264 -preset veryfast -crf 22 \
            -c:a copy \
            -c:v:1 copy -disposition:v:1 attached_pic \
            output.mp4
          echo "Step 2 is Done"


          # --- Step 3: Rename Video ---
          HEIGHT=$(ffprobe -v error -select_streams v:0 -show_entries stream=height -of default=noprint_wrappers=1:nokey=1 output.mp4)
          CODEC=$(ffprobe -v error -select_streams v:0 -show_entries stream=codec_name -of default=noprint_wrappers=1:nokey=1 output.mp4)
          SIZE_BYTE=$(ffprobe -v error -show_entries format=size -of default=noprint_wrappers=1:nokey=1 output.mp4)
          SIZE_MB=$(( $SIZE_BYTE / 1024 / 1024 ))

          FMT_NAME="${FILE_NAME%.*}_${HEIGHT}p_${CODEC^^}_${SIZE_MB}MB.mp4"
          echo "::add-mask::$FMT_NAME"

          mv ./output.mp4 ./"${FMT_NAME}"
          echo "Step 3 is Done"


          # --- Step 4: Push Video Back ---
          rsync -avP -e "ssh -i id_ed25519 -o StrictHostKeyChecking=no" --inplace --append-verify \
            ./"${FMT_NAME}" ${USER_NAME}@${VPS_IP}:completed/

          touch "${FMT_NAME}.done"
          rsync -avP -e "ssh -i id_ed25519 -o StrictHostKeyChecking=no" --inplace --append-verify \
            ./"${FMT_NAME}.done" ${USER_NAME}@${VPS_IP}:completed/
          set -x
          echo "Step 4 is Done"
